config/routes.rb
Prova2::Application.routes.draw do
  get "home/index"

 root :to=> "home#index"

  resources :turmis

  resources :telefones

  resources :disciplinaprofessors

  resources :professors

  resources :disciplinas

  resources :tipotelefones

  resources :alunos

end

app/models/aluno.rb
class Aluno < ActiveRecord::Base
  attr_accessible :matricula, :nomealuno, :sexo
end

app/models/disciplina.rb
class Disciplina < ActiveRecord::Base
  attr_accessible :cargahoraria, :nomedisciplina, :periodo, :sigla
end

app/models/disciplinaprofessor.rb
class Disciplinaprofessor < ActiveRecord::Base
  belongs_to :disciplina
  belongs_to :professor
  attr_accessible :disciplina_id, :professor_id, :ano, :periodo
end

app/models/professor.rb
class Professor < ActiveRecord::Base
  attr_accessible :nomeprofessor, :sexo
end

app/models/telefone.rb
class Telefone < ActiveRecord::Base
  belongs_to :aluno
  belongs_to :tipotelefone
  attr_accessible  :ddd, :numerotelefone
end

app/models/telefones.rb
class Telefone < ActiveRecord::Base
  belongs_to :aluno
  belongs_to :tipotelefone
  attr_accessible :aluno_id, :tipotelefone_id, :ddd, :numerotelefone
end

app/models/tipotelefone.rb
class Tipotelefone < ActiveRecord::Base
  attr_accessible :descricao
end

app/models/turmi.rb
class Turmi < ActiveRecord::Base
  belongs_to :aluno
  belongs_to :disciplinaprofessor
  attr_accessible :aluno_id, :disciplinaprofessor_id
end

app/controllers/alunos_controller.rb
class AlunosController < InheritedResources::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/professors_controller.rb
class ProfessorsController < InheritedResources::Base
end

app/controllers/telefones_controller.rb
class TelefonesController < InheritedResources::Base
end

app/controllers/tipotelefones_controller.rb
class TipotelefonesController < InheritedResources::Base
end

app/controllers/turmis_controller.rb
class TurmisController < InheritedResources::Base
end

app/helpers/alunos_helper.rb
module AlunosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/disciplinas_helper.rb
module DisciplinasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/helpers/telefones_helper.rb
module TelefonesHelper
end

app/helpers/tipotelefones_helper.rb
module TipotelefonesHelper
end

app/helpers/turmis_helper.rb
module TurmisHelper
end

app/views/tipotelefones/_form.html.haml
=semantic_form_for [@tipotelefone] do |form|
   
   =form.input :descricao, :label => 'Descricao'
   
   =form.submit 'Salvar'

app/views/tipotelefones/edit.html.erb
<h1>Editar tipotelefone</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @tipotelefone %> |
<%= link_to 'Voltar', tipotelefones_path %>

app/views/tipotelefones/index.html.erb
<h1>Lista de tipotelefones</h1>

<table>
  <tr>
    <th>Descrição</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tipotelefones.each do |tipotelefone| %>
  <tr>
    <td><%= tipotelefone.descricao %></td>
    <td><%= link_to 'Mostrar', tipotelefone %></td>
    <td><%= link_to 'Editar', edit_tipotelefone_path(tipotelefone) %></td>
    <td><%= link_to 'Excluir', tipotelefone, method: :delete, data: { confirm: 'Você tem certeza ?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tipotelefone', new_tipotelefone_path %>

app/views/tipotelefones/new.html.erb
<h1>Novo tipotelefone</h1>

<%= render 'form' %>

<%= link_to 'Voltar', tipotelefones_path %>

app/views/tipotelefones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Descricao:</b>
  <%= @tipotelefone.descricao %>
</p>


<%= link_to 'Editar', edit_tipotelefone_path(@tipotelefone) %> |
<%= link_to 'Voltar', tipotelefones_path %>