config/routes.rb
Prova2::Application.routes.draw do
  get "home/index"

 root :to=> "home#index"

  resources :turmis

  resources :telefones

  resources :disciplinaprofessors

  resources :professors

  resources :disciplinas

  resources :tipotelefones

  resources :alunos

end

app/models/aluno.rb
class Aluno < ActiveRecord::Base
  attr_accessible :matricula, :nomealuno, :sexo
end

app/models/disciplina.rb
class Disciplina < ActiveRecord::Base
  attr_accessible :cargahoraria, :nomedisciplina, :periodo, :sigla
end

app/models/disciplinaprofessor.rb
class Disciplinaprofessor < ActiveRecord::Base
  belongs_to :disciplina
  belongs_to :professor
  attr_accessible :disciplina_id, :professor_id, :ano, :periodo
end

app/models/professor.rb
class Professor < ActiveRecord::Base
  attr_accessible :nomeprofessor, :sexo
end

app/models/telefone.rb
class Telefone < ActiveRecord::Base
  belongs_to :aluno
  belongs_to :tipotelefone
  attr_accessible  :ddd, :numerotelefone
end

app/models/telefones.rb
class Telefone < ActiveRecord::Base
  belongs_to :aluno
  belongs_to :tipotelefone
  attr_accessible :aluno_id, :tipotelefone_id, :ddd, :numerotelefone
end

app/models/tipotelefone.rb
class Tipotelefone < ActiveRecord::Base
  attr_accessible :descricao
end

app/models/turmi.rb
class Turmi < ActiveRecord::Base
  belongs_to :aluno
  belongs_to :disciplinaprofessor
  attr_accessible :aluno_id, :disciplinaprofessor_id
end

app/controllers/alunos_controller.rb
class AlunosController < InheritedResources::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/disciplinas_controller.rb
class DisciplinasController < InheritedResources::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/professors_controller.rb
class ProfessorsController < InheritedResources::Base
end

app/controllers/telefones_controller.rb
class TelefonesController < InheritedResources::Base
end

app/controllers/turmis_controller.rb
class TurmisController < InheritedResources::Base
end

app/helpers/alunos_helper.rb
module AlunosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/disciplinas_helper.rb
module DisciplinasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/helpers/telefones_helper.rb
module TelefonesHelper
end

app/helpers/tipotelefones_helper.rb
module TipotelefonesHelper
end

app/helpers/turmis_helper.rb
module TurmisHelper
end

app/views/alunos/_form.html.haml
=semantic_form_for [@aluno] do |form|
   
   =form.input :matricula, :label => 'Matricula'
   =form.input :nomealuno, :label => 'NomeAluno'
   =form.input :sexo, :label => 'Sexo'
   =form.submit 'Salvar'

app/views/alunos/edit.html.erb
<h1>Editar aluno</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @aluno %> |
<%= link_to 'Voltar', alunos_path %>

app/views/alunos/index.html.erb
<h1>Listas de alunos</h1>

<table>
  <tr>
    <th>Matricula</th>
    <th>Nomealuno</th>
    <th>Sexo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @alunos.each do |aluno| %>
  <tr>
    <td><%= aluno.matricula %></td>
    <td><%= aluno.nomealuno %></td>
    <td><%= aluno.sexo %></td>
    <td><%= link_to 'Mostrar', aluno %></td>
    <td><%= link_to 'Editar', edit_aluno_path(aluno) %></td>
    <td><%= link_to 'Excluir', aluno, method: :delete, data: { confirm: 'Você tem certeza ?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Aluno', new_aluno_path %>

app/views/alunos/new.html.erb
<h1>Novo aluno</h1>

<%= render 'form' %>

<%= link_to 'Voltar', alunos_path %>

app/views/alunos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Matricula:</b>
  <%= @aluno.matricula %>
</p>

<p>
  <b>NomeAluno:</b>
  <%= @aluno.nomealuno %>
</p>

<p>
  <b>Sexo:</b>
  <%= @aluno.sexo %>
</p>


<%= link_to 'Editar', edit_aluno_path(@aluno) %> |
<%= link_to 'Voltar', alunos_path %>

app/views/disciplinas/_form.html.haml
=semantic_form_for [@disciplina] do |form|
   
   =form.input :nomedisciplina, :label => 'NomeDisciplina'
   =form.input :sigla, :label => 'Sigla'
   =form.input :cargahoraria, :label => 'CargaHoraria'
   =form.input :periodo, :label => 'Periodo'
   =form.submit 'Salvar'

app/views/disciplinas/edit.html.erb
<h1>Editar disciplina</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @disciplina %> |
<%= link_to 'Voltar', disciplinas_path %>

app/views/disciplinas/index.html.erb
<h1>Listas de disciplinas</h1>

<table>
  <tr>
    <th>Nomedisciplina</th>
    <th>Sigla</th>
    <th>Cargahoraria</th>
    <th>Periodo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @disciplinas.each do |disciplina| %>
  <tr>
    <td><%= disciplina.nomedisciplina %></td>
    <td><%= disciplina.sigla %></td>
    <td><%= disciplina.cargahoraria %></td>
    <td><%= disciplina.periodo %></td>
    <td><%= link_to 'Mostrar', disciplina %></td>
    <td><%= link_to 'Editar', edit_disciplina_path(disciplina) %></td>
    <td><%= link_to 'Excluir', disciplina, method: :delete, data: { confirm: 'Você tem certeza ?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Disciplina', new_disciplina_path %>

app/views/disciplinas/new.html.erb
<h1>Nova disciplina</h1>

<%= render 'form' %>

<%= link_to 'Voltar', disciplinas_path %>

app/views/disciplinas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>NomeDisciplina:</b>
  <%= @disciplina.nomedisciplina %>
</p>

<p>
  <b>Sigla:</b>
  <%= @disciplina.sigla %>
</p>

<p>
  <b>CargaHoraria:</b>
  <%= @disciplina.cargahoraria %>
</p>

<p>
  <b>Periodo:</b>
  <%= @disciplina.periodo %>
</p>


<%= link_to 'Editar', edit_disciplina_path(@disciplina) %> |
<%= link_to 'Voltar', disciplinas_path %>

app/views/professors/_form.html.haml
=semantic_form_for [@professor] do |form|
   
   =form.input :nomeprofessor, :label => 'NomeProfessor'
   =form.input :sexo, :label => 'Sexo'
   =form.submit 'Salvar'

app/views/professors/edit.html.erb
<h1>Editar professor</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @professor %> |
<%= link_to 'Voltar', professors_path %>

app/views/professors/index.html.erb
<h1>Lista de professores</h1>

<table>
  <tr>
    <th>Nomeprofessor</th>
    <th>Sexo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @professors.each do |professor| %>
  <tr>
    <td><%= professor.nomeprofessor %></td>
    <td><%= professor.sexo %></td>
    <td><%= link_to 'Mostrar', professor %></td>
    <td><%= link_to 'Editar', edit_professor_path(professor) %></td>
    <td><%= link_to 'Excluir', professor, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Professor', new_professor_path %>

app/views/professors/new.html.erb
<h1>Novo professor</h1>

<%= render 'form' %>

<%= link_to 'Voltar', professors_path %>

app/views/professors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>NomeProfessor:</b>
  <%= @professor.nomeprofessor %>
</p>

<p>
  <b>Sexo:</b>
  <%= @professor.sexo %>
</p>


<%= link_to 'Editar', edit_professor_path(@professor) %> |
<%= link_to 'Voltar', professors_path %>

app/views/turmis/_form.html.haml
= semantic_form_for [@turmi] do |form|
  
   = form.input :aluno, :member_label => :nomealuno, :label => 'Aluno' 
   = form.input :disciplinaprofessor, :member_label => :ano, :label => 'Disciplinaprofessor' 
   = form.submit 'Salvar'

app/views/turmis/edit.html.erb
<h1>Editar turma</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @turmi %> |
<%= link_to 'Voltar', turmis_path %>

app/views/turmis/index.html.erb
<h1>Lista de turmas</h1>

<table>
  <tr>
    <th>Aluno</th>
    <th>Disciplinaprofessor</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @turmis.each do |turmi| %>
  <tr>
    <td><%= turmi.aluno %></td>
    <td><%= turmi.disciplinaprofessor %></td>
    <td><%= link_to 'Mostrar', turmi %></td>
    <td><%= link_to 'Editar', edit_turmi_path(turmi) %></td>
    <td><%= link_to 'Excluir', turmi, method: :delete, data: { confirm: 'Você tem certeza ?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nova Turma', new_turmi_path %>

app/views/turmis/new.html.erb
<h1>Nova turma</h1>

<%= render 'form' %>

<%= link_to 'Voltar', turmis_path %>

app/views/turmis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Aluno:</b>
  <%= @turmi.aluno.nomealuno %>
</p>

<p>
  <b>Disciplinaprofessor:</b>
  <%= @turmi.disciplinaprofessor.ano %>
</p>


<%= link_to 'Editar', edit_turmi_path(@turmi) %> |
<%= link_to 'Voltar', turmis_path %>