config/routes.rb
Prova2::Application.routes.draw do
  get "home/index"

 root :to=> "home#index"

  resources :turmis

  resources :telefones

  resources :disciplinaprofessors

  resources :professors

  resources :disciplinas

  resources :tipotelefones

  resources :alunos

end

app/models/aluno.rb
class Aluno < ActiveRecord::Base
  attr_accessible :matricula, :nomealuno, :sexo
end

app/models/disciplina.rb
class Disciplina < ActiveRecord::Base
  attr_accessible :cargahoraria, :nomedisciplina, :periodo, :sigla
end

app/models/disciplinaprofessor.rb
class Disciplinaprofessor < ActiveRecord::Base
  belongs_to :disciplina
  belongs_to :professor
  attr_accessible :disciplina_id, :professor_id, :ano, :periodo
end

app/models/professor.rb
class Professor < ActiveRecord::Base
  attr_accessible :nomeprofessor, :sexo
end

app/models/telefone.rb
class Telefone < ActiveRecord::Base
  belongs_to :aluno
  belongs_to :tipotelefone
  attr_accessible  :ddd, :numerotelefone
end

app/models/telefones.rb
class Telefone < ActiveRecord::Base
  belongs_to :aluno
  belongs_to :tipotelefone
  attr_accessible :aluno_id, :tipotelefone_id, :ddd, :numerotelefone
end

app/models/tipotelefone.rb
class Tipotelefone < ActiveRecord::Base
  attr_accessible :descricao
end

app/models/turmi.rb
class Turmi < ActiveRecord::Base
  belongs_to :aluno
  belongs_to :disciplinaprofessor
  attr_accessible :aluno_id, :disciplinaprofessor_id
end

app/controllers/alunos_controller.rb
class AlunosController < InheritedResources::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/disciplinas_controller.rb
class DisciplinasController < InheritedResources::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/professors_controller.rb
class ProfessorsController < InheritedResources::Base
end

app/controllers/telefones_controller.rb
class TelefonesController < InheritedResources::Base
end

app/controllers/turmis_controller.rb
class TurmisController < InheritedResources::Base
end

app/helpers/alunos_helper.rb
module AlunosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/disciplinaprofessors_helper.rb
module DisciplinaprofessorsHelper
end

app/helpers/disciplinas_helper.rb
module DisciplinasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/helpers/telefones_helper.rb
module TelefonesHelper
end

app/helpers/tipotelefones_helper.rb
module TipotelefonesHelper
end

app/helpers/turmis_helper.rb
module TurmisHelper
end

app/views/telefones/_form.html.haml
= semantic_form_for [@telefone] do |form|
  
   = form.input :ddd, :label => 'Ddd'
   = form.input :numerotelefone, :label => 'Numerotelefone'
   = form.input :aluno, :member_label => :nomealuno, :label => 'Aluno' 
   = form.input :tipotelefone, :member_label => :descricao, :label => 'Descricao' 
   = form.submit 'Salvar'

app/views/telefones/edit.html.erb
<h1>Editar telefone</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @telefone %> |
<%= link_to 'Voltar', telefones_path %>

app/views/telefones/index.html.erb
<h1>Lista de telefones</h1>

<table>
  <tr>
    <th>Ddd</th>
    <th>Numerotelefone</th>
    <th>Aluno</th>
    <th>Tipotelefone</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @telefones.each do |telefone| %>
  <tr>
    <td><%= telefone.ddd %></td>
    <td><%= telefone.numerotelefone %></td>
    <td><%= telefone.aluno %></td>
    <td><%= telefone.tipotelefone %></td>
    <td><%= link_to 'Mostrar', telefone %></td>
    <td><%= link_to 'Editar', edit_telefone_path(telefone) %></td>
    <td><%= link_to 'Excluir', telefone, method: :delete, data: { confirm: 'Você tem certeza ?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Novo Telefone', new_telefone_path %>

app/views/telefones/new.html.erb
<h1>Novo telefone</h1>

<%= render 'form' %>

<%= link_to 'Voltar', telefones_path %>

app/views/telefones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Ddd:</b>
  <%= @telefone.ddd %>
</p>

<p>
  <b>Numerotelefone:</b>
  <%= @telefone.numerotelefone %>
</p>

<p>
  <b>Aluno:</b>
  <%= @telefone.aluno.nomealuno %>
</p>

<p>
  <b>Tipotelefone:</b>
  <%= @telefone.tipotelefone.descricao %>
</p>


<%= link_to 'Editar', edit_telefone_path(@telefone) %> |
<%= link_to 'Voltar', telefones_path %>