config/routes.rb
Prova2::Application.routes.draw do
  get "home/index"

 root :to=> "home#index"

  resources :turmis

  resources :telefones

  resources :disciplinaprofessors

  resources :professors

  resources :disciplinas

  resources :tipotelefones

  resources :alunos

end

app/models/aluno.rb
class Aluno < ActiveRecord::Base
  attr_accessible :matricula, :nomealuno, :sexo
end

app/models/disciplina.rb
class Disciplina < ActiveRecord::Base
  attr_accessible :cargahoraria, :nomedisciplina, :periodo, :sigla
end

app/models/disciplinaprofessor.rb
class Disciplinaprofessor < ActiveRecord::Base
  belongs_to :disciplina
  belongs_to :professor
  attr_accessible :disciplina_id, :professor_id, :ano, :periodo
end

app/models/professor.rb
class Professor < ActiveRecord::Base
  attr_accessible :nomeprofessor, :sexo
end

app/models/telefone.rb
class Telefone < ActiveRecord::Base
  belongs_to :aluno
  belongs_to :tipotelefone
  attr_accessible  :ddd, :numerotelefone
end

app/models/telefones.rb
class Telefone < ActiveRecord::Base
  belongs_to :aluno
  belongs_to :tipotelefone
  attr_accessible :aluno_id, :tipotelefone_id, :ddd, :numerotelefone
end

app/models/tipotelefone.rb
class Tipotelefone < ActiveRecord::Base
  attr_accessible :descricao
end

app/models/turmi.rb
class Turmi < ActiveRecord::Base
  belongs_to :aluno
  belongs_to :disciplinaprofessor
  attr_accessible :aluno_id, :disciplinaprofessor_id
end

app/controllers/alunos_controller.rb
class AlunosController < InheritedResources::Base
end

app/controllers/disciplinaprofessors_controller.rb
class DisciplinaprofessorsController < InheritedResources::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/professors_controller.rb
class ProfessorsController < InheritedResources::Base
end

app/controllers/telefones_controller.rb
class TelefonesController < InheritedResources::Base
end

app/controllers/turmis_controller.rb
class TurmisController < InheritedResources::Base
end

app/helpers/alunos_helper.rb
module AlunosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/disciplinaprofessors_helper.rb
module DisciplinaprofessorsHelper
end

app/helpers/disciplinas_helper.rb
module DisciplinasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/helpers/telefones_helper.rb
module TelefonesHelper
end

app/helpers/tipotelefones_helper.rb
module TipotelefonesHelper
end

app/helpers/turmis_helper.rb
module TurmisHelper
end

app/views/disciplinaprofessors/_form.html.haml
= semantic_form_for [@disciplinaprofessor] do |form|
  
   = form.input :ano, :label => 'Ano'
   = form.input :periodo, :label => 'Periodo'
   = form.input :disciplina, :member_label => :nomedisciplina, :label => 'Disciplina' 
   = form.input :professor, :member_label => :nomeprofessor, :label => 'Professor' 
   = form.submit 'Salvar'

app/views/disciplinaprofessors/edit.html.erb
<h1>Editar disciplina professor</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @disciplinaprofessor %> |
<%= link_to 'Voltar', disciplinaprofessors_path %>

app/views/disciplinaprofessors/index.html.erb
<h1>Listas disciplina professores</h1>

<table>
  <tr>
    <th>Ano</th>
    <th>Periodo</th>
    <th>Disciplina</th>
    <th>Professor</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @disciplinaprofessors.each do |disciplinaprofessor| %>
  <tr>
    <td><%= disciplinaprofessor.ano %></td>
    <td><%= disciplinaprofessor.periodo %></td>
    <td><%= disciplinaprofessor.disciplina %></td>
    <td><%= disciplinaprofessor.professor %></td>
    <td><%= link_to 'Mostrar', disciplinaprofessor %></td>
    <td><%= link_to 'Editar', edit_disciplinaprofessor_path(disciplinaprofessor) %></td>
    <td><%= link_to 'Excluir', disciplinaprofessor, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Disciplinaprofessor', new_disciplinaprofessor_path %>

app/views/disciplinaprofessors/new.html.erb
<h1>Nova disciplina professor</h1>

<%= render 'form' %>

<%= link_to 'Voltar', disciplinaprofessors_path %>

app/views/disciplinaprofessors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Ano:</b>
  <%= @disciplinaprofessor.ano %>
</p>

<p>
  <b>Periodo:</b>
  <%= @disciplinaprofessor.periodo %>
</p>

<p>
  <b>Disciplina:</b>
  <%= @disciplinaprofessor.disciplina.nomedisciplina %>
</p>

<p>
  <b>Professor:</b>
  <%= @disciplinaprofessor.professor.nomeprofessor %>
</p>


<%= link_to 'Editar', edit_disciplinaprofessor_path(@disciplinaprofessor) %> |
<%= link_to 'Voltar', disciplinaprofessors_path %>